In [109]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

In [110]:
iris = pd.read_csv("iris.csv")

In [111]:
iris.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
145,146,6.7,3.0,5.2,2.3,Iris-virginica
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
116,117,6.5,3.0,5.5,1.8,Iris-virginica
26,27,5.0,3.4,1.6,0.4,Iris-setosa

In [112]:
iris.shape

(150, 6)

In [113]:
iris.duplicated().sum() # there are 3 duplicated values

np.int64(0)

In [114]:
iris.drop_duplicates(inplace=True)

In [115]:
iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [116]:
iris["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [117]:
iris["Species"]=iris["Species"].map({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2})

In [118]:
X = iris.drop(columns=["Species"])
y = iris["Species"]

In [119]:
X.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [120]:
# train test split
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [121]:
model = LogisticRegression(max_iter=10000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [122]:
y_pred = model.predict(X_test)
print("accuracy score: ",accuracy_score(y_test,y_pred))
print("precision score: ",precision_score(y_test,y_pred,average='macro'))
print("recall score: ",recall_score(y_test,y_pred,average='macro'))

accuracy score:  1.0
precision score:  1.0
recall score:  1.0

In [123]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [124]:
y_pred = model.predict(X_test)
print("accuracy score: ",accuracy_score(y_test,y_pred))
print("precision score: ",precision_score(y_test,y_pred,average='macro'))
print("recall score: ",recall_score(y_test,y_pred,average='macro'))

accuracy score:  1.0
precision score:  1.0
recall score:  1.0

In [125]:
pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('knn',KNeighborsClassifier())
])

param_grid = {"knn__n_neighbors":[3,5,7,9]}

model = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
)

model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("accuracy score: ",accuracy_score(y_test,y_pred))
print("precision score: ",precision_score(y_test,y_pred,average='macro'))
print("recall score: ",recall_score(y_test,y_pred,average='macro'))

accuracy score:  1.0
precision score:  1.0
recall score:  1.0